version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    commit-message:
      prefix: 'Bump'

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    commit-message:
      prefix: 'Bump'
    groups:
      dev-dependencies:
        dependency-type: 'development'
